// All data for the Kavya Jaiswal profile - no backend needed.

import type {
  BenchmarkData,
  GeneratedProject,
  JobMatch,
  Profile,
  ProfileBundle,
  ResumeRecord,
  RiskPrediction,
  Roadmap,
  ScoreBreakdown,
  SkillGapAnalysis,
} from './backend';

export const PROTOTYPE_MODE = true;
export const PROTOTYPE_TOKEN = 'prototype-token-kavya-2026';

export const KAVYA_PROFILE: Profile = {
  id: 'kavya-prototype-001',
  full_name: 'Kavya Jaiswal',
  email: '1@zerogap.com',
  avatar_url: 'https://avatars.githubusercontent.com/kavyajaiswal007',
  role: 'student',
  college_name: 'NIET Greater Noida',
  degree: 'B.Tech Information Technology',
  graduation_year: 2026,
  location: 'Greater Noida, Uttar Pradesh',
  bio: 'Full Stack Developer building ZeroGap - a career intelligence platform for 200+ students.',
  learning_style: 'project-based',
  time_availability_hours: 4,
  github_username: 'kavyajaiswal007',
  linkedin_url: 'https://linkedin.com/in/kavyajaiswal007',
  github_access_token: null,
  onboarding_completed: true,
  created_at: '2025-09-01T00:00:00Z',
  updated_at: new Date().toISOString(),
};

export const KAVYA_BUNDLE: ProfileBundle = {
  profile: KAVYA_PROFILE,
  target_roles: [{
    id: 'role-001',
    user_id: 'kavya-prototype-001',
    job_title: 'Full Stack Developer',
    specialization: 'Product engineering & AI-integrated web apps',
    experience_level: 'fresher',
    is_active: true,
    created_at: '2025-09-01T00:00:00Z',
  }],
  skills: [
    { id: 's1', user_id: 'kavya-prototype-001', skill_name: 'React', proficiency_level: 88, verified: true, proof_type: 'github', proof_url: 'https://github.com/kavyajaiswal007', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's2', user_id: 'kavya-prototype-001', skill_name: 'JavaScript', proficiency_level: 90, verified: true, proof_type: 'github', proof_url: 'https://github.com/kavyajaiswal007', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's3', user_id: 'kavya-prototype-001', skill_name: 'TypeScript', proficiency_level: 74, verified: true, proof_type: 'project', proof_url: 'https://zerogap-frontend-002.vercel.app', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's4', user_id: 'kavya-prototype-001', skill_name: 'Node.js', proficiency_level: 78, verified: true, proof_type: 'project', proof_url: 'https://zerogap-frontend-002.vercel.app', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's5', user_id: 'kavya-prototype-001', skill_name: 'Tailwind CSS', proficiency_level: 92, verified: true, proof_type: 'project', proof_url: 'https://zerogap-frontend-002.vercel.app', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's6', user_id: 'kavya-prototype-001', skill_name: 'Supabase', proficiency_level: 84, verified: true, proof_type: 'project', proof_url: 'https://zerogap-frontend-002.vercel.app', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's7', user_id: 'kavya-prototype-001', skill_name: 'REST API Design', proficiency_level: 82, verified: true, proof_type: 'project', proof_url: 'https://zerogap-frontend-002.vercel.app', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's8', user_id: 'kavya-prototype-001', skill_name: 'Git & GitHub', proficiency_level: 88, verified: true, proof_type: 'github', proof_url: 'https://github.com/kavyajaiswal007', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's9', user_id: 'kavya-prototype-001', skill_name: 'HTML & CSS', proficiency_level: 94, verified: true, proof_type: 'github', proof_url: 'https://github.com/kavyajaiswal007', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's10', user_id: 'kavya-prototype-001', skill_name: 'Next.js', proficiency_level: 62, verified: true, proof_type: 'project', proof_url: 'https://zerogap-frontend-002.vercel.app', last_updated: '2026-04-01T00:00:00Z' },
    { id: 's11', user_id: 'kavya-prototype-001', skill_name: 'PostgreSQL', proficiency_level: 66, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-04-01T00:00:00Z' },
    { id: 's12', user_id: 'kavya-prototype-001', skill_name: 'Docker', proficiency_level: 44, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-04-01T00:00:00Z' },
    { id: 's13', user_id: 'kavya-prototype-001', skill_name: 'System Design', proficiency_level: 52, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-04-01T00:00:00Z' },
    { id: 's14', user_id: 'kavya-prototype-001', skill_name: 'Testing (Jest)', proficiency_level: 48, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-04-01T00:00:00Z' },
    { id: 's15', user_id: 'kavya-prototype-001', skill_name: 'Python Basics', proficiency_level: 58, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-04-01T00:00:00Z' },
  ],
  certificates: [
    { id: 'c1', title: 'React', issuer: 'YouTube - Codevolution', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    { id: 'c2', title: 'Node.js', issuer: 'YouTube - Traversy Media', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    { id: 'c3', title: 'TypeScript', issuer: 'YouTube - Dave Gray', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    { id: 'c4', title: 'Tailwind CSS', issuer: 'YouTube - Traversy Media', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    { id: 'c5', title: 'Full Stack Development', issuer: 'YouTube - JS Mastery', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    { id: 'c6', title: 'Git & GitHub', issuer: 'YouTube - Traversy Media', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    { id: 'c7', title: 'PostgreSQL', issuer: 'YouTube - Amigoscode', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    { id: 'c8', title: 'System Design', issuer: 'YouTube - Gaurav Sen', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
  ],
  github_proofs: [
    { id: 'g1', repo_name: 'zerogap', repo_url: 'https://github.com/kavyajaiswal007/zerogap', quality_score: 94, skills_detected: ['React', 'TypeScript', 'Node.js', 'Supabase', 'Redis'] },
    { id: 'g2', repo_name: 'ai-resume-builder', repo_url: 'https://github.com/kavyajaiswal007/ai-resume-builder', quality_score: 88, skills_detected: ['React', 'TypeScript', 'Claude API', 'PDFKit'] },
    { id: 'g3', repo_name: 'learnpath-engine', repo_url: 'https://github.com/kavyajaiswal007/learnpath-engine', quality_score: 86, skills_detected: ['React', 'Express', 'Supabase', 'YouTube API'] },
    { id: 'g4', repo_name: 'placement-tracker', repo_url: 'https://github.com/kavyajaiswal007/placement-tracker', quality_score: 82, skills_detected: ['React', 'TypeScript', 'Supabase', 'Chart.js'] },
  ],
  xp: {
    id: 'xp1',
    user_id: 'kavya-prototype-001',
    total_xp: 5340,
    current_level: 11,
    current_streak_days: 2,
    longest_streak_days: 2,
    last_active_date: new Date().toISOString().slice(0, 10),
    updated_at: new Date().toISOString(),
  },
};

export const KAVYA_SCORE: ScoreBreakdown = {
  skillsMatchPercentage: 82,
  projectQualityScore: 76,
  activityConsistencyScore: 81,
  finalScore: 79,
};

export const KAVYA_ANALYSIS: SkillGapAnalysis = {
  id: 'analysis-001',
  user_id: 'kavya-prototype-001',
  target_role_id: 'role-001',
  skill_score: 79,
  matched_skills: ['React', 'JavaScript', 'TypeScript', 'Node.js', 'Tailwind CSS', 'Supabase', 'REST API Design', 'Git & GitHub', 'HTML & CSS', 'Next.js'],
  missing_skills: ['Docker', 'Redis', 'Kubernetes', 'GraphQL', 'CI/CD Pipelines'],
  partial_skills: ['PostgreSQL', 'System Design', 'Testing (Jest)', 'Python Basics'],
  skills_match_percentage: 82,
  project_quality_score: 76,
  activity_consistency_score: 81,
  analysis_data: {
    recommended_resources: [
      { title: 'Docker Complete Course', type: 'playlist', url: 'https://youtube.com/playlist?list=PLWKjhJtqVAblpP3C6q6Yx2S5Z7Z7Z7Z7Z', reason: 'Closes your top Docker gap' },
      { title: 'System Design Masterclass', type: 'playlist', url: 'https://youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX', reason: 'Core interviews skill' },
    ],
    estimated_readiness_weeks: 6,
  },
  created_at: new Date().toISOString(),
};

export const KAVYA_BENCHMARK: BenchmarkData = {
  id: 'bench-001',
  user_id: 'kavya-prototype-001',
  target_role: 'Full Stack Developer',
  college_name: 'NIET Greater Noida',
  college_percentile: 89,
  branch_percentile: 86,
  national_percentile: 81,
  avg_college_score: 58,
  avg_national_score: 61,
  ranking_data: { total_role_users: 12840, total_college_users: 418 },
  calculated_at: new Date().toISOString(),
};

export const KAVYA_RISK: RiskPrediction = {
  id: 'risk-001',
  user_id: 'kavya-prototype-001',
  risk_level: 'low',
  ready_in_months: 2,
  risk_factors: ['Docker not yet in portfolio', 'System Design needs proof project'],
  action_suggestions: [
    'Containerise ZeroGap with Docker Compose this week',
    'Write a 1-page architecture doc for your GitHub README',
    'Apply to the top 3 job matches before Friday',
  ],
  success_probability: 81,
  predicted_at: new Date().toISOString(),
};

export const KAVYA_JOBS: JobMatch[] = [
  {
    id: 'jm1',
    user_id: 'kavya-prototype-001',
    job_listing_id: 'j1',
    fit_percentage: 94,
    missing_skills: ['Docker'],
    next_steps: ['Add Docker to ZeroGap repo'],
    match_reason: 'Strong React + TypeScript + Node.js match',
    saved: true,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'j1',
      title: 'Full Stack Developer - React + Node.js',
      source: 'curated',
      company: 'Razorpay',
      location: 'Bengaluru, India',
      apply_url: 'https://razorpay.com/jobs/',
      is_active: true,
      posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Build merchant-facing dashboards and APIs for a high-scale fintech platform.',
      external_id: 'razorpay-fsd-001',
      salary_range: 'INR 10-24 LPA',
      salary_lpa_min: 10,
      salary_lpa_max: 24,
      skills_required: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'REST API', 'Git'],
      job_type: 'Full-time',
      experience_required: 'Fresher/0-2 years',
      is_remote: false,
      company_logo: null,
      qualifications: 'B.Tech CSE/IT 2024-2026',
      highlights: { Responsibilities: ['Build product features', 'Ship measurable improvements'], Qualifications: ['React', 'Node.js', 'TypeScript'], Benefits: ['Mentorship', 'Fast growth team'] },
    },
  },
  {
    id: 'jm2',
    user_id: 'kavya-prototype-001',
    job_listing_id: 'j2',
    fit_percentage: 89,
    missing_skills: ['Testing (Jest)', 'Docker'],
    next_steps: ['Add Jest tests to ZeroGap'],
    match_reason: 'React + TypeScript + CSS match for frontend platform role',
    saved: false,
    applied: true,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'j2',
      title: 'Software Engineer - Frontend Platform',
      source: 'curated',
      company: 'Zerodha',
      location: 'Remote, India',
      apply_url: 'https://zerodha.com/careers/',
      is_active: true,
      posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Improve frontend infrastructure, performance, and trading experiences.',
      external_id: 'zerodha-fe-001',
      salary_range: 'INR 12-28 LPA',
      salary_lpa_min: 12,
      salary_lpa_max: 28,
      skills_required: ['React', 'JavaScript', 'TypeScript', 'Testing (Jest)', 'CSS', 'Git'],
      job_type: 'Full-time',
      experience_required: 'Fresher/0-2 years',
      is_remote: true,
      company_logo: null,
      qualifications: 'B.Tech 2024-2026',
      highlights: { Responsibilities: ['Ship UI improvements'], Qualifications: ['React', 'TypeScript'], Benefits: ['Remote', 'Fast growth'] },
    },
  },
  {
    id: 'jm3',
    user_id: 'kavya-prototype-001',
    job_listing_id: 'j3',
    fit_percentage: 85,
    missing_skills: ['Docker', 'Redis'],
    next_steps: ['Add Redis caching proof to GitHub'],
    match_reason: 'Node.js + Express + Supabase match',
    saved: false,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'j3',
      title: 'Full Stack Engineer - Student Products',
      source: 'curated',
      company: 'Unacademy',
      location: 'Bengaluru, India',
      apply_url: 'https://unacademy.com/careers',
      is_active: true,
      posted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Own learner-facing product modules and API integrations.',
      external_id: 'unacademy-fse-001',
      salary_range: 'INR 9-22 LPA',
      salary_lpa_min: 9,
      salary_lpa_max: 22,
      skills_required: ['React', 'Node.js', 'Express', 'MongoDB', 'REST API', 'Git'],
      job_type: 'Full-time',
      experience_required: 'Fresher/0-2 years',
      is_remote: false,
      company_logo: null,
      qualifications: 'B.Tech 2024-2026',
      highlights: { Responsibilities: ['Build product modules'], Qualifications: ['React', 'Node.js'], Benefits: ['Mentorship'] },
    },
  },
  {
    id: 'jm4',
    user_id: 'kavya-prototype-001',
    job_listing_id: 'j4',
    fit_percentage: 80,
    missing_skills: ['Docker', 'Testing (Jest)'],
    next_steps: ['Add Docker + Jest to resume'],
    match_reason: 'React + TypeScript + PostgreSQL stack match',
    saved: false,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'j4',
      title: 'Software Developer - SaaS Dashboard',
      source: 'curated',
      company: 'Freshworks',
      location: 'Chennai, India',
      apply_url: 'https://www.freshworks.com/company/careers/',
      is_active: true,
      posted_at: new Date(Date.now() - 5 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Build SaaS dashboards and backend-backed workflows for business teams.',
      external_id: 'freshworks-sd-001',
      salary_range: 'INR 8-20 LPA',
      salary_lpa_min: 8,
      salary_lpa_max: 20,
      skills_required: ['React', 'TypeScript', 'PostgreSQL', 'Docker', 'Testing (Jest)', 'CSS'],
      job_type: 'Full-time',
      experience_required: 'Fresher/0-2 years',
      is_remote: false,
      company_logo: null,
      qualifications: 'B.Tech 2024-2026',
      highlights: { Responsibilities: ['Build dashboards'], Qualifications: ['React', 'TypeScript'], Benefits: ['Hybrid'] },
    },
  },
  {
    id: 'jm5',
    user_id: 'kavya-prototype-001',
    job_listing_id: 'j5',
    fit_percentage: 76,
    missing_skills: ['Performance Optimization'],
    next_steps: ['Add Lighthouse score screenshot to portfolio'],
    match_reason: 'Tailwind CSS + TypeScript + React match for growth role',
    saved: false,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'j5',
      title: 'Frontend Engineer - Growth',
      source: 'curated',
      company: 'CRED',
      location: 'Bengaluru, India',
      apply_url: 'https://cred.club/careers',
      is_active: true,
      posted_at: new Date(Date.now() - 6 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Ship polished growth experiments and onboarding funnels.',
      external_id: 'cred-fe-001',
      salary_range: 'INR 14-32 LPA',
      salary_lpa_min: 14,
      salary_lpa_max: 32,
      skills_required: ['React', 'TypeScript', 'Tailwind CSS', 'Performance Optimization', 'REST API', 'Git'],
      job_type: 'Full-time',
      experience_required: 'Fresher/0-2 years',
      is_remote: false,
      company_logo: null,
      qualifications: 'B.Tech 2024-2026',
      highlights: { Responsibilities: ['Ship growth features'], Qualifications: ['React', 'Tailwind'], Benefits: ['High comp'] },
    },
  },
];

const now = new Date().toISOString();

export const KAVYA_ROADMAP: Roadmap = {
  id: 'roadmap-001',
  user_id: 'kavya-prototype-001',
  target_role_id: 'role-001',
  title: 'Full Stack Developer Job-Ready Roadmap',
  total_stages: 4,
  estimated_weeks: 8,
  is_active: true,
  completion_percentage: 62,
  generated_by_ai: true,
  created_at: '2026-02-01T00:00:00Z',
  updated_at: now,
  stages: [
    {
      id: 'stage-1',
      roadmap_id: 'roadmap-001',
      stage_number: 1,
      title: 'Product Foundations',
      description: 'Lock React, TypeScript, REST APIs, and UI polish.',
      skills_to_learn: ['React', 'TypeScript', 'REST API'],
      resources: [{ name: 'React Full Course - Codevolution', url: 'https://youtube.com/playlist?list=PLu0W_9lII9agx66oZnT6-n3iF1k9s2g4K', type: 'video', platform: 'YouTube', is_free: true }],
      projects: [{ name: 'ZeroGap Dashboard', description: 'Full-stack career platform', skills_practiced: ['React', 'TypeScript', 'Node.js'], difficulty: 'advanced' }],
      estimated_weeks: 2,
      is_completed: true,
      completion_percentage: 100,
      order_index: 1,
      tasks: [
        { id: 't1', stage_id: 'stage-1', user_id: 'kavya-prototype-001', title: 'Revise React hooks and state patterns', description: '', task_type: 'learn', resource_url: 'https://youtube.com/playlist?list=PLu0W_9lII9agx66oZnT6-n3iF1k9s2g4K', estimated_hours: 4, is_completed: true, completed_at: '2026-02-10T00:00:00Z', proof_url: 'https://github.com/kavyajaiswal007/zerogap', xp_reward: 70, created_at: '2026-02-01T00:00:00Z' },
        { id: 't2', stage_id: 'stage-1', user_id: 'kavya-prototype-001', title: 'Build ZeroGap dashboard shell', description: '', task_type: 'build', resource_url: null, estimated_hours: 8, is_completed: true, completed_at: '2026-02-14T00:00:00Z', proof_url: 'https://zerogap-frontend-002.vercel.app', xp_reward: 90, created_at: '2026-02-01T00:00:00Z' },
        { id: 't3', stage_id: 'stage-1', user_id: 'kavya-prototype-001', title: 'Push proof to GitHub with README', description: '', task_type: 'practice', resource_url: null, estimated_hours: 2, is_completed: true, completed_at: '2026-02-16T00:00:00Z', proof_url: 'https://github.com/kavyajaiswal007/zerogap', xp_reward: 60, created_at: '2026-02-01T00:00:00Z' },
      ],
    },
    {
      id: 'stage-2',
      roadmap_id: 'roadmap-001',
      stage_number: 2,
      title: 'Backend + Database Sprint',
      description: 'Build reliable APIs, auth, and database workflows.',
      skills_to_learn: ['Node.js', 'PostgreSQL', 'Supabase'],
      resources: [{ name: 'Node.js & Express Course', url: 'https://youtube.com/playlist?list=PLGLfVvz_LVvT7c8d9e0f1g2h3i4j5k6l7', type: 'video', platform: 'YouTube', is_free: true }],
      projects: [{ name: 'AI Resume Builder', description: 'ATS resume with Claude API', skills_practiced: ['Node.js', 'TypeScript', 'Claude API'], difficulty: 'advanced' }],
      estimated_weeks: 2,
      is_completed: true,
      completion_percentage: 100,
      order_index: 2,
      tasks: [
        { id: 't4', stage_id: 'stage-2', user_id: 'kavya-prototype-001', title: 'Build REST API with Node + Express', description: '', task_type: 'build', resource_url: null, estimated_hours: 6, is_completed: true, completed_at: '2026-03-01T00:00:00Z', proof_url: 'https://github.com/kavyajaiswal007/zerogap', xp_reward: 100, created_at: '2026-02-20T00:00:00Z' },
        { id: 't5', stage_id: 'stage-2', user_id: 'kavya-prototype-001', title: 'Integrate Supabase + PostgreSQL', description: '', task_type: 'build', resource_url: null, estimated_hours: 5, is_completed: true, completed_at: '2026-03-05T00:00:00Z', proof_url: 'https://github.com/kavyajaiswal007/zerogap', xp_reward: 80, created_at: '2026-02-20T00:00:00Z' },
        { id: 't6', stage_id: 'stage-2', user_id: 'kavya-prototype-001', title: 'Deploy backend to Render', description: '', task_type: 'apply', resource_url: null, estimated_hours: 2, is_completed: true, completed_at: '2026-03-08T00:00:00Z', proof_url: 'https://zerogap-frontend-002.vercel.app', xp_reward: 70, created_at: '2026-02-20T00:00:00Z' },
      ],
    },
    {
      id: 'stage-3',
      roadmap_id: 'roadmap-001',
      stage_number: 3,
      title: 'System Design + DevOps',
      description: 'Add Docker, CI/CD, and architecture documentation.',
      skills_to_learn: ['Docker', 'CI/CD', 'System Design'],
      resources: [
        { name: 'Docker Complete Course', url: 'https://youtube.com/playlist?list=PLWKjhJtqVAblpP3C6q6Yx2S5Z7Z7Z7Z7Z', type: 'video', platform: 'YouTube', is_free: true },
        { name: 'System Design Masterclass', url: 'https://youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX', type: 'video', platform: 'YouTube', is_free: true },
      ],
      projects: [{ name: 'Containerised ZeroGap', description: 'Docker Compose for full stack', skills_practiced: ['Docker', 'CI/CD'], difficulty: 'intermediate' }],
      estimated_weeks: 2,
      is_completed: false,
      completion_percentage: 40,
      order_index: 3,
      tasks: [
        { id: 't7', stage_id: 'stage-3', user_id: 'kavya-prototype-001', title: 'Write architecture doc for ZeroGap', description: '', task_type: 'practice', resource_url: null, estimated_hours: 3, is_completed: true, completed_at: '2026-04-10T00:00:00Z', proof_url: 'https://github.com/kavyajaiswal007/zerogap', xp_reward: 60, created_at: '2026-03-20T00:00:00Z' },
        { id: 't8', stage_id: 'stage-3', user_id: 'kavya-prototype-001', title: 'Containerise app with Docker Compose', description: '', task_type: 'build', resource_url: null, estimated_hours: 5, is_completed: false, completed_at: null, proof_url: null, xp_reward: 90, created_at: '2026-03-20T00:00:00Z' },
        { id: 't9', stage_id: 'stage-3', user_id: 'kavya-prototype-001', title: 'Add GitHub Actions CI/CD pipeline', description: '', task_type: 'build', resource_url: null, estimated_hours: 4, is_completed: false, completed_at: null, proof_url: null, xp_reward: 80, created_at: '2026-03-20T00:00:00Z' },
      ],
    },
    {
      id: 'stage-4',
      roadmap_id: 'roadmap-001',
      stage_number: 4,
      title: 'Interview + Apply',
      description: 'Apply to roles with tailored proof and a tight resume.',
      skills_to_learn: ['Resume', 'Interview Prep', 'Job Applications'],
      resources: [],
      projects: [],
      estimated_weeks: 2,
      is_completed: false,
      completion_percentage: 10,
      order_index: 4,
      tasks: [
        { id: 't10', stage_id: 'stage-4', user_id: 'kavya-prototype-001', title: 'Tailor ATS resume for top 5 jobs', description: '', task_type: 'apply', resource_url: null, estimated_hours: 3, is_completed: false, completed_at: null, proof_url: null, xp_reward: 80, created_at: '2026-04-01T00:00:00Z' },
        { id: 't11', stage_id: 'stage-4', user_id: 'kavya-prototype-001', title: 'Complete one mock interview', description: '', task_type: 'practice', resource_url: null, estimated_hours: 2, is_completed: false, completed_at: null, proof_url: null, xp_reward: 70, created_at: '2026-04-01T00:00:00Z' },
      ],
    },
  ],
};

export const KAVYA_RESUME: ResumeRecord = {
  id: 'resume-001',
  user_id: 'kavya-prototype-001',
  target_role_id: 'role-001',
  ats_score: 87,
  keyword_match_score: 82,
  pdf_url: null,
  version: 1,
  is_latest: true,
  created_at: new Date().toISOString(),
  content_json: {
    basics: { name: 'Kavya Jaiswal', email: '1@zerogap.com', phone: '+91 96969 78007', location: 'Greater Noida, Uttar Pradesh', linkedin: 'https://linkedin.com/in/kavyajaiswal007', github: 'https://github.com/kavyajaiswal007', portfolio: 'https://zerogap-frontend-002.vercel.app' },
    summary: 'Full Stack Developer and B.Tech IT student at NIET Greater Noida (2026) with production experience in React, TypeScript, Node.js, Supabase, and Tailwind CSS. Built ZeroGap - a career intelligence platform used by 200+ students - from design to deployment. Ranked top 19% nationally for Full Stack readiness. Seeking engineering roles at product-driven teams where ownership, speed, and impact are valued.',
    skills: {
      technical: ['React 18, TypeScript, JavaScript ES6+, Next.js, HTML5, CSS3', 'Node.js, Express.js, REST API Design, JWT Auth, WebSockets', 'Supabase, PostgreSQL, Redis, Prisma ORM', 'Framer Motion, Tailwind CSS, Responsive UI, Component Libraries'],
      tools: ['Git', 'GitHub', 'Vercel', 'Render', 'Postman', 'VS Code', 'Figma', 'Notion', 'Linux Terminal'],
      soft: ['Product Thinking', 'Technical Documentation', 'Team Collaboration', 'Problem Solving', 'Ownership Mindset'],
    },
    education: [{ degree: 'B.Tech - Information Technology', institution: 'NIET (Noida Institute of Engineering and Technology)', location: 'Greater Noida, UP', graduation: 'June 2026', cgpa: '8.4/10', relevant_courses: ['Data Structures & Algorithms', 'Database Management Systems', 'Operating Systems', 'Computer Networks', 'Web Technologies'] }],
    experience: [
      { title: 'Full Stack Developer', company: 'ZeroGap (Self-directed Product Build)', location: 'Greater Noida / Remote', start_date: 'Sep 2025', end_date: 'Present', bullets: ['Architected and shipped ZeroGap - a 15-module career intelligence platform - covering skill gap AI, roadmap engine, AI resume builder, job matching, peer benchmarks, execution tracker, mentor chat, and LearnPath with certificate generation.', 'Built 12+ production API routes using Node.js + Express + Supabase with JWT auth, Redis caching, rate limiting, and background job queues.', 'Implemented AI-powered features using Anthropic Claude API: skill gap analysis, resume generation, roadmap planning, and quiz MCQ creation for 100+ YouTube playlists.', 'Deployed on Vercel + Render with CI/CD; platform handles 200+ student profiles with sub-2s dashboard load times.'] },
      { title: 'Frontend Developer Intern', company: 'Campus Innovation Cell - NIET', location: 'Greater Noida', start_date: 'Jun 2025', end_date: 'Aug 2025', bullets: ['Built a React + TypeScript student placement tracking dashboard for 300+ students with real-time filters, CSV export, and PDF generation.', 'Reduced manual placement reporting time by 60% through automation of weekly batch summaries and role-wise analytics views.', 'Delivered 3 UI components adopted by other student project teams.'] },
    ],
    projects: [
      { name: 'ZeroGap Employability Platform', tech_stack: 'React, TypeScript, Node.js, Supabase, Redis, OpenAI, Tailwind CSS', github_url: 'https://github.com/kavyajaiswal007/zerogap', live_url: 'https://zerogap-frontend-002.vercel.app', bullets: ['15-module career platform: skill gap AI, roadmap, resume builder, job matching, peer benchmarks, tracker, mentor chat, YouTube certification engine.', 'Integrated Claude API for 4 intelligent features - skill analysis, resume generation, roadmap planning, quiz creation for 100+ playlists.', 'Served 200+ student profiles with sub-2s load using Redis caching and parallel API calls.'] },
      { name: 'AI Resume Builder & ATS Scorer', tech_stack: 'React, TypeScript, Node.js, Claude API, PDFKit, Supabase', github_url: 'https://github.com/kavyajaiswal007/ai-resume-builder', live_url: 'https://zerogap-frontend-002.vercel.app/resume', bullets: ['Generates 2-page ATS-optimized resumes with role-specific keywords, quantified bullets, and market-aligned skills.', 'ATS scoring engine evaluates 6 resume dimensions and generates improvement suggestions.', 'Job comparison feature calculates resume fit % against any listing.'] },
      { name: 'LearnPath Certification Engine', tech_stack: 'React, TypeScript, Express, Supabase, YouTube API, PDFKit', github_url: 'https://github.com/kavyajaiswal007/learnpath-engine', live_url: 'https://zerogap-frontend-002.vercel.app/learn', bullets: ['60+ YouTube playlists across 10 skill domains with gap-to-playlist routing.', 'Per-video MCQ quiz engine with 10 conceptual questions per video using Claude AI.', 'Certificate generation with verifiable codes and LinkedIn share.'] },
      { name: 'Student Placement Tracker', tech_stack: 'React, TypeScript, Supabase, Chart.js, Tailwind CSS', github_url: 'https://github.com/kavyajaiswal007/placement-tracker', live_url: '', bullets: ['300+ NIET student profiles with role-wise analytics and recruiter-ready PDF export.', 'Reduced weekly reporting effort by 60%.', 'Supabase RLS ensuring data privacy.'] },
    ],
    certifications: [
      { name: 'React', issuer: 'YouTube - Codevolution', date: 'Jan 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
      { name: 'Node.js', issuer: 'YouTube - Traversy Media', date: 'Feb 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
      { name: 'TypeScript', issuer: 'YouTube - Dave Gray', date: 'Feb 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
      { name: 'Tailwind CSS', issuer: 'YouTube - Traversy Media', date: 'Mar 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
      { name: 'Full Stack Development', issuer: 'YouTube - JS Mastery', date: 'Mar 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
      { name: 'Git & GitHub', issuer: 'YouTube - Traversy Media', date: 'Apr 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
      { name: 'PostgreSQL', issuer: 'YouTube - Amigoscode', date: 'Apr 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
      { name: 'System Design', issuer: 'YouTube - Gaurav Sen', date: 'May 2026', credential_url: 'https://linkedin.com/in/kavyajaiswal007' },
    ],
    achievements: [
      '2-day execution streak with 5,340+ XP earned through roadmap tasks, GitHub commits, and project walkthroughs.',
      'Ranked top 19% nationally for Full Stack Developer readiness across 12,800+ student profiles.',
      'Built ZeroGap - 15-module career platform - solo; adopted by 200+ NIET students for placement preparation.',
      'Completed 8 YouTube certification courses across React, Node.js, TypeScript, Tailwind CSS, SQL, Git, System Design, and MERN Stack.',
      'Top 11 in NIET IT department readiness benchmarks (418 students indexed).',
    ],
    extracurricular: [
      { title: 'Technical Team Member', organization: 'Google Developer Student Club - NIET', duration: '2024-2025', description: 'Conducted 3 React + Supabase workshops for 80+ students.' },
      { title: 'Hackathon Finalist', organization: 'Smart India Hackathon 2024 - Internal Round', duration: '2024', description: 'Built AI attendance system in 36 hours. Reached internal finals.' },
      { title: 'Core Member', organization: 'NIET Coding Club', duration: '2023-Present', description: 'Organized DSA sessions, reviewed 15+ GitHub repos, mentored juniors.' },
    ],
    languages: ['English (Professional)', 'Hindi (Native)'],
    ats_keywords_injected: ['React', 'TypeScript', 'Node.js', 'REST API', 'PostgreSQL', 'Supabase', 'Redis', 'Git', 'Tailwind CSS', 'System Design', 'Full Stack', 'JavaScript', 'Express', 'Authentication', 'Deployment'],
  },
};

export const KAVYA_PROJECTS: GeneratedProject[] = [
  { id: 'p1', user_id: 'kavya-prototype-001', project_title: 'ZeroGap Employability Platform', description: 'Full-stack career intelligence platform with AI skill gap analysis, roadmap engine, resume builder, job matching, peer benchmarks, execution tracker, mentor chat, and YouTube playlist certification engine. Used by 200+ students from NIET.', tech_stack: ['React', 'TypeScript', 'Node.js', 'Supabase', 'Redis', 'Claude API', 'Tailwind CSS'], skills_practiced: ['React', 'TypeScript', 'Node.js', 'Supabase', 'Redis'], difficulty_level: 'advanced', starter_code_url: 'https://github.com/kavyajaiswal007/zerogap', github_template_url: 'https://github.com/kavyajaiswal007/zerogap', step_by_step_guide: ['Define product scope and user personas', 'Design schema, API contract, and core UI states', 'Build MVP with auth, dashboard, and proof capture', 'Add AI features using Claude API', 'Add analytics, tests, and deployment notes', 'Ship live walkthrough and write README'], is_github_ready: true, created_at: '2025-09-01T00:00:00Z' },
  { id: 'p2', user_id: 'kavya-prototype-001', project_title: 'AI Resume Builder & ATS Scorer', description: 'Generates 2-page ATS-optimized resumes from user profile data using Claude AI. Scores keywords, compares against job listings, and exports production-ready PDFs.', tech_stack: ['React', 'TypeScript', 'Node.js', 'Anthropic Claude', 'PDFKit', 'Supabase'], skills_practiced: ['React', 'Node.js', 'Claude API', 'PDFKit'], difficulty_level: 'advanced', starter_code_url: 'https://github.com/kavyajaiswal007/ai-resume-builder', github_template_url: 'https://github.com/kavyajaiswal007/ai-resume-builder', step_by_step_guide: ['Build profile data aggregator', 'Design Claude prompt for 2-page resume', 'Add ATS scoring engine', 'Build PDF export', 'Add job comparison feature'], is_github_ready: true, created_at: '2025-11-01T00:00:00Z' },
  { id: 'p3', user_id: 'kavya-prototype-001', project_title: 'LearnPath Certification Engine', description: 'YouTube playlist curation system with per-video MCQ quizzes powered by AI, streak tracking, XP system, and downloadable PDF certificates.', tech_stack: ['React', 'TypeScript', 'Express', 'Supabase', 'YouTube Data API', 'PDFKit'], skills_practiced: ['React', 'Express', 'Supabase', 'YouTube API'], difficulty_level: 'intermediate', starter_code_url: 'https://github.com/kavyajaiswal007/learnpath-engine', github_template_url: 'https://github.com/kavyajaiswal007/learnpath-engine', step_by_step_guide: ['Seed 60+ YouTube playlists', 'Build per-video quiz engine', 'Add streak + XP system', 'Build certificate PDF generator', 'Add LinkedIn share URL'], is_github_ready: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'p4', user_id: 'kavya-prototype-001', project_title: 'Student Placement Tracker Dashboard', description: 'Real-time placement tracking for 300+ NIET students with role-wise analytics, CSV export, and recruiter-ready PDF generation. Reduced reporting time by 60%.', tech_stack: ['React', 'TypeScript', 'Supabase', 'Chart.js', 'Tailwind CSS'], skills_practiced: ['React', 'TypeScript', 'Supabase', 'Data Visualization'], difficulty_level: 'intermediate', starter_code_url: 'https://github.com/kavyajaiswal007/placement-tracker', github_template_url: 'https://github.com/kavyajaiswal007/placement-tracker', step_by_step_guide: ['Design student data schema', 'Build dashboard with filters', 'Add CSV and PDF export', 'Implement Supabase RLS', 'Deploy to Vercel'], is_github_ready: true, created_at: '2025-06-01T00:00:00Z' },
];

export const KAVYA_PLAYLISTS = [
  { id: 'pl1', yt_playlist_id: 'PLu0W_9lII9agx66oZnT6-n3iF1k9s2g4K', title: 'React JS Full Course', channel_name: 'Codevolution', thumbnail_url: 'https://i.ytimg.com/vi/QFaFIcGhPoM/hqdefault.jpg', total_videos: 30, total_duration_seconds: 27000, skill_tags: ['React', 'JavaScript', 'Hooks'], difficulty: 'beginner' as const, category: 'Web Development - Frontend', is_enrolled: true, completion_percentage: 100, match_score: 0.98 },
  { id: 'pl2', yt_playlist_id: 'PL0Zuz27SZ-6Oi6xNtL_fwCrwpuqylMsgT', title: 'JavaScript Full Course', channel_name: 'Dave Gray', thumbnail_url: 'https://i.ytimg.com/vi/EfAl9bwzVZk/hqdefault.jpg', total_videos: 26, total_duration_seconds: 43200, skill_tags: ['JavaScript', 'ES6', 'DOM'], difficulty: 'beginner' as const, category: 'Web Development - Frontend', is_enrolled: true, completion_percentage: 100, match_score: 0.95 },
  { id: 'pl3', yt_playlist_id: 'PLGLfVvz_LVvTn3cK5e6LjhgGiSeVlIRwt', title: 'TypeScript Full Course', channel_name: 'Derek Banas', thumbnail_url: 'https://i.ytimg.com/vi/2pZmKW9-I_k/hqdefault.jpg', total_videos: 18, total_duration_seconds: 21600, skill_tags: ['TypeScript', 'Interfaces', 'Generics'], difficulty: 'intermediate' as const, category: 'Web Development - Frontend', is_enrolled: true, completion_percentage: 100, match_score: 0.96 },
  { id: 'pl4', yt_playlist_id: 'PLBZBJbE_rGRWeh5mIBhD-hhDwSEDxogDg', title: 'Tailwind CSS Complete Course', channel_name: 'Traversy Media', thumbnail_url: 'https://i.ytimg.com/vi/UBOj6rqRUME/hqdefault.jpg', total_videos: 8, total_duration_seconds: 14400, skill_tags: ['Tailwind CSS', 'UI Design'], difficulty: 'beginner' as const, category: 'Web Development - Frontend', is_enrolled: true, completion_percentage: 100, match_score: 0.97 },
  { id: 'pl5', yt_playlist_id: 'PLGLfVvz_LVvT7c8d9e0f1g2h3i4j5k6l7', title: 'Node.js & Express Full Course', channel_name: 'Traversy Media', thumbnail_url: 'https://i.ytimg.com/vi/fBNz5xF-Kx4/hqdefault.jpg', total_videos: 20, total_duration_seconds: 28800, skill_tags: ['Node.js', 'Express', 'REST API'], difficulty: 'beginner' as const, category: 'Web Development - Backend', is_enrolled: true, completion_percentage: 100, match_score: 0.94 },
  { id: 'pl6', yt_playlist_id: 'PLgFHb8dDZq1c1y4p2Zp4yC6h0vR9bZ1mY', title: 'PostgreSQL Complete Tutorial', channel_name: 'Amigoscode', thumbnail_url: 'https://i.ytimg.com/vi/qw--VYLpxG4/hqdefault.jpg', total_videos: 12, total_duration_seconds: 14400, skill_tags: ['PostgreSQL', 'SQL', 'Joins'], difficulty: 'beginner' as const, category: 'Databases', is_enrolled: true, completion_percentage: 100, match_score: 0.87 },
  { id: 'pl7', yt_playlist_id: 'PLZPZq0r_RZOMx7l8v9w1c2k3l4m5n6o7', title: 'Git & GitHub Complete Course', channel_name: 'Traversy Media', thumbnail_url: 'https://i.ytimg.com/vi/SWYqp7iY_Tc/hqdefault.jpg', total_videos: 14, total_duration_seconds: 10800, skill_tags: ['Git', 'GitHub', 'Version Control'], difficulty: 'beginner' as const, category: 'Soft Skills & Career', is_enrolled: true, completion_percentage: 100, match_score: 0.92 },
  { id: 'pl8', yt_playlist_id: 'PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX', title: 'System Design Masterclass', channel_name: 'Gaurav Sen', thumbnail_url: 'https://i.ytimg.com/vi/quLrc3PbuIw/hqdefault.jpg', total_videos: 25, total_duration_seconds: 36000, skill_tags: ['System Design', 'Architecture', 'Scalability'], difficulty: 'advanced' as const, category: 'System Design', is_enrolled: true, completion_percentage: 72, match_score: 0.93 },
  { id: 'pl9', yt_playlist_id: 'PLWKjhJtqVAblpP3C6q6Yx2S5Z7Z7Z7Z7Z', title: 'Docker Complete Course', channel_name: 'TechWorld with Nana', thumbnail_url: 'https://i.ytimg.com/vi/3c-iBn73dDE/hqdefault.jpg', total_videos: 20, total_duration_seconds: 25200, skill_tags: ['Docker', 'Containers', 'DevOps'], difficulty: 'beginner' as const, category: 'DevOps & Cloud', is_enrolled: false, completion_percentage: 0, match_score: 0.91 },
  { id: 'pl10', yt_playlist_id: 'PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA', title: 'DSA with Java', channel_name: 'CodeWithHarry', thumbnail_url: 'https://i.ytimg.com/vi/AT14lCXuMKI/hqdefault.jpg', total_videos: 60, total_duration_seconds: 72000, skill_tags: ['DSA', 'Java', 'Interview Prep'], difficulty: 'intermediate' as const, category: 'DSA & CS Fundamentals', is_enrolled: false, completion_percentage: 0, match_score: 0.78 },
  { id: 'pl11', yt_playlist_id: 'PLZoTAELRMXVMdJ5sqbCK2LiM0HhQVWNzm', title: 'TensorFlow 2.0 Complete Course', channel_name: 'freeCodeCamp', thumbnail_url: 'https://i.ytimg.com/vi/tPYj3fFJGjk/hqdefault.jpg', total_videos: 20, total_duration_seconds: 43200, skill_tags: ['TensorFlow', 'Deep Learning', 'Python'], difficulty: 'intermediate' as const, category: 'Data Science & ML', is_enrolled: false, completion_percentage: 0, match_score: 0.65 },
  { id: 'pl12', yt_playlist_id: 'PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q', title: 'Android Dev with Kotlin', channel_name: 'Philipp Lackner', thumbnail_url: 'https://i.ytimg.com/vi/EExSSotojVI/hqdefault.jpg', total_videos: 35, total_duration_seconds: 63000, skill_tags: ['Android', 'Kotlin', 'Mobile'], difficulty: 'beginner' as const, category: 'Mobile Development', is_enrolled: false, completion_percentage: 0, match_score: 0.60 },
];

export const KAVYA_ACTIVITY_GRAPH: { date: string }[] = Array.from({ length: 2 }, (_, index) => {
  const date = new Date();
  date.setDate(date.getDate() - (1 - index));
  return { date: date.toISOString().slice(0, 10) };
});

export const KAVYA_CHAT = [
  { role: 'user', content: 'What should I focus on this week to get placed?' },
  { role: 'assistant', content: "You're at 79% readiness - very close. This week: (1) Containerise ZeroGap with Docker Compose and push a commit, (2) Tailor your resume to the Razorpay and Zerodha listings in your Hire Me tab, (3) Record a 90-second walkthrough of the AI Resume Builder. That moves you from strong portfolio to recruiter-ready proof." },
  { role: 'user', content: 'Which of my projects should I show first in interviews?' },
  { role: 'assistant', content: "Lead with ZeroGap. It proves React + TypeScript + Node.js + AI integration + production deployment - the exact stack Razorpay, Zerodha, and CRED are hiring for. Frame it: 'I identified a real problem for 200+ students, designed the system, built and shipped it solo in 8 months, and it's live.' That's a complete product engineering story." },
  { role: 'user', content: 'Am I ready to apply to Razorpay?' },
  { role: 'assistant', content: "You match 10 of 12 required skills. Your gaps are Docker and Redis - both are in your 'close' category. Apply now and mention you're actively upskilling in containerisation. Your ZeroGap project, 2-day streak, and 8 certifications make you a strong candidate. Send today - use the resume PDF from the Resume tab. Your ATS score is 87." },
];
