// Dr. Vineet Kumar Verma — Account Data

import type {
  BenchmarkData,
  GeneratedProject,
  JobMatch,
  Profile,
  ProfileBundle,
  ResumeRecord,
  RiskPrediction,
  Roadmap,
  ScoreBreakdown,
  SkillGapAnalysis,
} from './backend';

export const VINEET_TOKEN = 'session-token-vineet-2026';

export const VINEET_PROFILE: Profile = {
  id: 'vineet-001',
  full_name: 'Dr. Vineet Kumar Verma',
  email: 'vineetkumarverma@zerogap.in',
  avatar_url: 'https://media.licdn.com/dms/image/v2/C5603AQGi9w5ZvGiflQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517022965697',
  role: 'mentor',
  college_name: 'Babu Banarasi Das National Institute of Technology and Management',
  degree: 'Ph.D — Computer Science & Engineering',
  graduation_year: 2014,
  location: 'Lucknow, Uttar Pradesh',
  bio: 'Academic leader, researcher, and CFO-level strategist in EdTech. 10+ years bridging the gap between academic depth and industry readiness.',
  learning_style: 'structured-theory-to-practice',
  time_availability_hours: 3,
  github_username: null,
  linkedin_url: 'https://www.linkedin.com/in/dr-vineet-kumar-verma-90b99a13/',
  github_access_token: null,
  onboarding_completed: true,
  created_at: '2024-06-01T00:00:00Z',
  updated_at: new Date().toISOString(),
};

export const VINEET_BUNDLE: ProfileBundle = {
  profile: VINEET_PROFILE,
  target_roles: [
    {
      id: 'vr-001',
      user_id: 'vineet-001',
      job_title: 'Chief Technology Officer (CTO)',
      specialization: 'EdTech Strategy, AI Integration, Academic-Industry Bridge',
      experience_level: 'senior',
      is_active: true,
      created_at: '2024-06-01T00:00:00Z',
    },
    {
      id: 'vr-002',
      user_id: 'vineet-001',
      job_title: 'EdTech Product Head',
      specialization: 'Learning platform design, curriculum engineering, AI-powered education',
      experience_level: 'senior',
      is_active: false,
      created_at: '2024-06-01T00:00:00Z',
    },
  ],
  skills: [
    { id: 'vs1', user_id: 'vineet-001', skill_name: 'Research & Academic Writing', proficiency_level: 96, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs2', user_id: 'vineet-001', skill_name: 'Curriculum Design & Engineering', proficiency_level: 94, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs3', user_id: 'vineet-001', skill_name: 'Leadership & Team Management', proficiency_level: 90, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs4', user_id: 'vineet-001', skill_name: 'Data Analysis & Interpretation', proficiency_level: 88, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs5', user_id: 'vineet-001', skill_name: 'Strategic Planning', proficiency_level: 87, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs6', user_id: 'vineet-001', skill_name: 'Stakeholder Communication', proficiency_level: 92, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs7', user_id: 'vineet-001', skill_name: 'Machine Learning Concepts', proficiency_level: 78, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs8', user_id: 'vineet-001', skill_name: 'Python (Scripting & Data)', proficiency_level: 72, verified: true, proof_type: 'project', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs9', user_id: 'vineet-001', skill_name: 'SQL & Database Design', proficiency_level: 74, verified: true, proof_type: 'self_declared', proof_url: null, last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs10', user_id: 'vineet-001', skill_name: 'EdTech Product Thinking', proficiency_level: 89, verified: true, proof_type: 'certificate', proof_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', last_updated: '2026-01-01T00:00:00Z' },
    { id: 'vs11', user_id: 'vineet-001', skill_name: 'React (Fundamentals)', proficiency_level: 42, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-03-01T00:00:00Z' },
    { id: 'vs12', user_id: 'vineet-001', skill_name: 'Node.js & REST APIs', proficiency_level: 38, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-03-01T00:00:00Z' },
    { id: 'vs13', user_id: 'vineet-001', skill_name: 'System Design (High Level)', proficiency_level: 55, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-03-01T00:00:00Z' },
    { id: 'vs14', user_id: 'vineet-001', skill_name: 'Cloud Deployment (AWS/GCP)', proficiency_level: 30, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-03-01T00:00:00Z' },
    { id: 'vs15', user_id: 'vineet-001', skill_name: 'Docker & DevOps Basics', proficiency_level: 22, verified: false, proof_type: 'self_declared', proof_url: null, last_updated: '2026-03-01T00:00:00Z' },
  ],
  certificates: [
    { id: 'vc1', title: 'Ph.D — Computer Science & Engineering', issuer: 'BBDNITM Lucknow', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
    { id: 'vc2', title: 'NPTEL — Machine Learning', issuer: 'IIT Kharagpur via NPTEL', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
    { id: 'vc3', title: 'Data Science Specialization', issuer: 'Coursera — Johns Hopkins', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
    { id: 'vc4', title: 'Leadership in Tech — Executive Program', issuer: 'IIM Lucknow', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
    { id: 'vc5', title: 'Python for Data Science', issuer: 'IBM via Coursera', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
  ],
  github_proofs: [],
  xp: {
    id: 'vxp1',
    user_id: 'vineet-001',
    total_xp: 2840,
    current_level: 7,
    current_streak_days: 3,
    longest_streak_days: 5,
    last_active_date: new Date().toISOString().slice(0, 10),
    updated_at: new Date().toISOString(),
  },
};

export const VINEET_SCORE: ScoreBreakdown = {
  skillsMatchPercentage: 68,
  projectQualityScore: 45,
  activityConsistencyScore: 70,
  finalScore: 62,
};

export const VINEET_ANALYSIS: SkillGapAnalysis = {
  id: 'vanalysis-001',
  user_id: 'vineet-001',
  target_role_id: 'vr-001',
  skill_score: 62,
  matched_skills: [
    'Research & Academic Writing',
    'Curriculum Design & Engineering',
    'Leadership & Team Management',
    'Data Analysis & Interpretation',
    'Strategic Planning',
    'Stakeholder Communication',
    'Machine Learning Concepts',
    'Python (Scripting & Data)',
    'EdTech Product Thinking',
  ],
  missing_skills: [
    'React / Frontend Development',
    'Cloud Deployment (AWS/GCP)',
    'Docker & DevOps',
    'GitHub Portfolio / Proof of Work',
    'Product Roadmapping Tools (Jira/Linear)',
  ],
  partial_skills: [
    'System Design (High Level)',
    'SQL & Database Design',
    'Node.js & REST APIs',
  ],
  skills_match_percentage: 68,
  project_quality_score: 45,
  activity_consistency_score: 70,
  analysis_data: {
    recommended_resources: [
      { title: 'Web Development Full Course — Apna College', type: 'playlist', url: 'https://youtube.com/playlist?list=PLGjplNEQ1it8-0CmoljS5yeV-GlKSUEt0', reason: 'Closes your #1 gap: practical web building' },
      { title: 'Node.js & Express Full Course — Traversy Media', type: 'playlist', url: 'https://youtube.com/playlist?list=PLillGF-RfqbYeckUaD1z6nviTp31GLTH8', reason: 'REST API and backend proof' },
      { title: 'Docker for Beginners — TechWorld with Nana', type: 'playlist', url: 'https://youtube.com/playlist?list=PLy7NrYWoggjzfAHlUusx2wuDwfCrmJYcs', reason: 'Closes DevOps gap — stand out from 90% candidates' },
      { title: 'System Design Masterclass — Gaurav Sen', type: 'playlist', url: 'https://youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX', reason: 'High-level architecture knowledge critical for CTO role' },
    ],
    estimated_readiness_weeks: 12,
  },
  created_at: new Date().toISOString(),
};

export const VINEET_BENCHMARK: BenchmarkData = {
  id: 'vbench-001',
  user_id: 'vineet-001',
  target_role: 'Chief Technology Officer (CTO)',
  college_name: 'BBDNITM Lucknow',
  college_percentile: 82,
  branch_percentile: 77,
  national_percentile: 68,
  avg_college_score: 54,
  avg_national_score: 59,
  ranking_data: { total_role_users: 4200, total_college_users: 86 },
  calculated_at: new Date().toISOString(),
};

export const VINEET_RISK: RiskPrediction = {
  id: 'vrisk-001',
  user_id: 'vineet-001',
  risk_level: 'medium',
  ready_in_months: 5,
  risk_factors: [
    'No GitHub portfolio or deployed project',
    'Cloud and DevOps skills below industry threshold',
    'Industry product execution proof missing',
    'React / frontend exposure is early stage',
  ],
  action_suggestions: [
    'Build and deploy 1 domain-specific project (Health Dashboard or Research Analyzer) in 30 days',
    'Complete Docker basics and containerise your first project',
    'Open a GitHub account this week and push your first repo',
    'Connect with 3 EdTech CTOs on LinkedIn and request 15-min informational chats',
  ],
  success_probability: 68,
  predicted_at: new Date().toISOString(),
};

export const VINEET_JOBS: JobMatch[] = [
  {
    id: 'vjm1',
    user_id: 'vineet-001',
    job_listing_id: 'vj1',
    fit_percentage: 88,
    missing_skills: ['GitHub Portfolio', 'Product Roadmapping Tool'],
    next_steps: ['Build 1 deployed EdTech project', 'Add LinkedIn case study post'],
    match_reason: 'Academic depth + ML knowledge + leadership exactly matches Research Analyst profile',
    saved: true,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'vj1',
      title: 'Research Analyst — AI & EdTech',
      source: 'curated',
      company: "BYJU'S / EduTech Ventures",
      location: 'Bengaluru / Remote',
      apply_url: 'https://byjus.com/careers/',
      is_active: true,
      posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Drive AI-powered learning content research and curriculum innovation strategy.',
      external_id: 'byjus-ra-001',
      salary_range: 'INR 18–32 LPA',
      salary_lpa_min: 18,
      salary_lpa_max: 32,
      skills_required: ['Research', 'Data Analysis', 'ML Concepts', 'Curriculum Design', 'Python', 'Communication'],
      job_type: 'Full-time',
      experience_required: '8+ years',
      is_remote: true,
      company_logo: null,
      qualifications: 'Ph.D or M.Tech preferred',
      highlights: {
        Responsibilities: ['Lead AI curriculum research', 'Publish domain insights', 'Mentor junior analysts'],
        Qualifications: ['Ph.D', 'ML exposure', 'EdTech background'],
        Benefits: ['Remote', 'High impact', 'Research budget'],
      },
    },
  },
  {
    id: 'vjm2',
    user_id: 'vineet-001',
    job_listing_id: 'vj2',
    fit_percentage: 84,
    missing_skills: ['React', 'Product Metrics (analytics tools)'],
    next_steps: ['Complete React fundamentals course', 'Build student analytics dashboard'],
    match_reason: 'EdTech product thinking + academic credibility + leadership fits VP Product profile',
    saved: false,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'vj2',
      title: 'VP Product — EdTech Platform',
      source: 'curated',
      company: 'Unacademy / Vedantu / Scaler',
      location: 'Bengaluru, India',
      apply_url: 'https://unacademy.com/careers',
      is_active: true,
      posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Own the learner journey from onboarding to mastery across web and mobile platforms.',
      external_id: 'unacademy-vpp-001',
      salary_range: 'INR 28–55 LPA',
      salary_lpa_min: 28,
      salary_lpa_max: 55,
      skills_required: ['Product Strategy', 'EdTech Domain', 'Data Analysis', 'Curriculum Design', 'Stakeholder Mgmt', 'Leadership'],
      job_type: 'Full-time',
      experience_required: '10+ years',
      is_remote: false,
      company_logo: null,
      qualifications: 'Ph.D/MBA preferred',
      highlights: {
        Responsibilities: ['Define product vision', 'Drive feature roadmap', 'Align academic & tech teams'],
        Qualifications: ['EdTech expertise', 'Leadership pedigree'],
        Benefits: ['ESOPs', 'High visibility'],
      },
    },
  },
  {
    id: 'vjm3',
    user_id: 'vineet-001',
    job_listing_id: 'vj3',
    fit_percentage: 80,
    missing_skills: ['Tech stack execution', 'Product deployment proof'],
    next_steps: ['Build and deploy a health or education platform project'],
    match_reason: 'Domain expertise + research credential + strategic planning directly match Consultant profile',
    saved: false,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'vj3',
      title: 'Technical Consultant — Digital Transformation',
      source: 'curated',
      company: 'Deloitte / Wipro / TCS Consulting',
      location: 'Delhi NCR / Hybrid',
      apply_url: 'https://www2.deloitte.com/in/en/careers.html',
      is_active: true,
      posted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Advise government and enterprise clients on AI adoption, EdTech rollout, and digital infrastructure.',
      external_id: 'deloitte-tc-001',
      salary_range: 'INR 22–42 LPA',
      salary_lpa_min: 22,
      salary_lpa_max: 42,
      skills_required: ['Strategic Planning', 'Research', 'Data Analysis', 'Communication', 'Domain Expertise', 'Python'],
      job_type: 'Full-time',
      experience_required: '8+ years',
      is_remote: false,
      company_logo: null,
      qualifications: 'Ph.D / MBA',
      highlights: {
        Responsibilities: ['Lead consulting engagements', 'Build client-facing reports', 'Guide AI implementation'],
        Qualifications: ['Research background', 'Presentation skills'],
        Benefits: ['Travel', 'High comp', 'Global exposure'],
      },
    },
  },
  {
    id: 'vjm4',
    user_id: 'vineet-001',
    job_listing_id: 'vj4',
    fit_percentage: 74,
    missing_skills: ['Docker', 'Cloud (AWS/GCP)', 'React', 'Deployment proof'],
    next_steps: ['Build 1 full-stack project with deployment', 'Learn Docker basics in 2 weeks'],
    match_reason: 'Academic + ML + Python base can grow into applied ML Engineer with 10-week bridge',
    saved: false,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'vj4',
      title: 'Applied ML Engineer (Senior)',
      source: 'curated',
      company: 'NASSCOM / AI Research Labs',
      location: 'Hyderabad / Remote',
      apply_url: 'https://nasscom.in/careers',
      is_active: true,
      posted_at: new Date(Date.now() - 5 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Translate ML research into production APIs and education technology products.',
      external_id: 'nasscom-ml-001',
      salary_range: 'INR 20–40 LPA',
      salary_lpa_min: 20,
      salary_lpa_max: 40,
      skills_required: ['Python', 'Machine Learning', 'REST APIs', 'Docker', 'Data Analysis', 'Research'],
      job_type: 'Full-time',
      experience_required: '6+ years',
      is_remote: true,
      company_logo: null,
      qualifications: 'Ph.D / M.Tech in CS',
      highlights: {
        Responsibilities: ['Build ML pipelines', 'Deploy models to production', 'Publish research'],
        Qualifications: ['Python proficiency', 'ML publications preferred'],
        Benefits: ['Remote', 'Research freedom'],
      },
    },
  },
  {
    id: 'vjm5',
    user_id: 'vineet-001',
    job_listing_id: 'vj5',
    fit_percentage: 70,
    missing_skills: ['Full-stack dev', 'GitHub portfolio', 'DevOps'],
    next_steps: ['Build an open-source EdTech tool and publish on GitHub'],
    match_reason: 'CFO-level thinking + domain + leadership matches CTO Academic profile with tech upskilling',
    saved: false,
    applied: false,
    created_at: new Date().toISOString(),
    job_listings: {
      id: 'vj5',
      title: 'Chief Technology Officer — EdTech Startup',
      source: 'curated',
      company: 'Series A EdTech Startup (Stealth)',
      location: 'Delhi NCR / Remote',
      apply_url: 'https://linkedin.com/jobs/',
      is_active: true,
      posted_at: new Date(Date.now() - 6 * 86400000).toISOString(),
      fetched_at: new Date().toISOString(),
      description: 'Lead technology strategy and execution for an AI-first learning platform targeting Tier-2 India.',
      external_id: 'startup-cto-001',
      salary_range: 'INR 35–70 LPA + ESOPs',
      salary_lpa_min: 35,
      salary_lpa_max: 70,
      skills_required: ['Tech Strategy', 'Leadership', 'Python', 'System Design', 'EdTech Product', 'Stakeholder Mgmt'],
      job_type: 'Full-time',
      experience_required: '10+ years',
      is_remote: true,
      company_logo: null,
      qualifications: 'Ph.D / M.Tech + Technical Leadership',
      highlights: {
        Responsibilities: ['Define tech vision', 'Hire and lead engineering team', 'Own platform architecture'],
        Qualifications: ['Proven tech leader', 'EdTech background a big plus'],
        Benefits: ['ESOPs', 'Co-founder track', 'Fully remote'],
      },
    },
  },
];

const vnow = new Date().toISOString();

export const VINEET_ROADMAP: Roadmap = {
  id: 'vroadmap-001',
  user_id: 'vineet-001',
  target_role_id: 'vr-001',
  title: 'CTO / EdTech Product Leader Transition Roadmap',
  total_stages: 4,
  estimated_weeks: 12,
  is_active: true,
  completion_percentage: 28,
  generated_by_ai: true,
  created_at: '2026-02-01T00:00:00Z',
  updated_at: vnow,
  stages: [
    {
      id: 'vstage-1',
      roadmap_id: 'vroadmap-001',
      stage_number: 1,
      title: 'Web & Code Foundation',
      description: 'Build confidence in HTML, CSS, JavaScript, and Python scripting. Goal: write code, not just read it.',
      skills_to_learn: ['HTML & CSS', 'JavaScript Basics', 'Python Scripting'],
      resources: [
        { name: 'Web Development Full Course — Apna College', url: 'https://youtube.com/playlist?list=PLGjplNEQ1it8-0CmoljS5yeV-GlKSUEt0', type: 'video', platform: 'YouTube', is_free: true },
        { name: 'JavaScript Full Course — CodeWithHarry', url: 'https://youtube.com/playlist?list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR', type: 'video', platform: 'YouTube', is_free: true },
      ],
      projects: [{ name: 'Personal Academic Portfolio Site', description: 'HTML + CSS website showcasing publications and research', skills_practiced: ['HTML', 'CSS', 'JavaScript'], difficulty: 'beginner' }],
      estimated_weeks: 2,
      is_completed: true,
      completion_percentage: 100,
      order_index: 1,
      tasks: [
        { id: 'vt1', stage_id: 'vstage-1', user_id: 'vineet-001', title: 'Complete HTML & CSS basics', description: 'Apna College Web Dev playlist — Phase 1', task_type: 'learn', resource_url: 'https://youtube.com/playlist?list=PLGjplNEQ1it8-0CmoljS5yeV-GlKSUEt0', estimated_hours: 6, is_completed: true, completed_at: '2026-02-14T00:00:00Z', proof_url: null, xp_reward: 60, created_at: '2026-02-01T00:00:00Z' },
        { id: 'vt2', stage_id: 'vstage-1', user_id: 'vineet-001', title: 'Build personal academic portfolio page', description: 'HTML + CSS site with publications, experience, and contact', task_type: 'build', resource_url: null, estimated_hours: 5, is_completed: true, completed_at: '2026-02-20T00:00:00Z', proof_url: null, xp_reward: 80, created_at: '2026-02-01T00:00:00Z' },
        { id: 'vt3', stage_id: 'vstage-1', user_id: 'vineet-001', title: 'Open GitHub account & push first project', description: 'Create GitHub profile, push portfolio code', task_type: 'apply', resource_url: null, estimated_hours: 2, is_completed: true, completed_at: '2026-02-22T00:00:00Z', proof_url: null, xp_reward: 70, created_at: '2026-02-01T00:00:00Z' },
      ],
    },
    {
      id: 'vstage-2',
      roadmap_id: 'vroadmap-001',
      stage_number: 2,
      title: 'Backend & Data Project',
      description: 'Connect your ML and data strengths to real systems. Build an API, store data, and deploy something live.',
      skills_to_learn: ['Node.js & Express', 'SQL / PostgreSQL', 'REST APIs'],
      resources: [
        { name: 'Node.js & Express — Thapa Technical', url: 'https://youtube.com/playlist?list=PLwGdqUZWnOp3t3qT7pvAznwUDzKbhEcCc', type: 'video', platform: 'YouTube', is_free: true },
        { name: 'MongoDB Tutorial — CodeWithHarry', url: 'https://youtube.com/playlist?list=PLu0W_9lII9agSt8AAfGPcQJv7_88RBEBB', type: 'video', platform: 'YouTube', is_free: true },
      ],
      projects: [{ name: 'Student Performance Tracker', description: 'Dashboard to track marks, grades, and recommendations for 100+ students', skills_practiced: ['Node.js', 'Express', 'MongoDB', 'REST API'], difficulty: 'intermediate' }],
      estimated_weeks: 3,
      is_completed: false,
      completion_percentage: 35,
      order_index: 2,
      tasks: [
        { id: 'vt4', stage_id: 'vstage-2', user_id: 'vineet-001', title: 'Complete Node.js + Express basics', description: 'Thapa Technical playlist — Weeks 3-4', task_type: 'learn', resource_url: 'https://youtube.com/playlist?list=PLwGdqUZWnOp3t3qT7pvAznwUDzKbhEcCc', estimated_hours: 8, is_completed: true, completed_at: '2026-03-10T00:00:00Z', proof_url: null, xp_reward: 80, created_at: '2026-02-25T00:00:00Z' },
        { id: 'vt5', stage_id: 'vstage-2', user_id: 'vineet-001', title: 'Build Student Performance Tracker API', description: 'Node + MongoDB + REST API', task_type: 'build', resource_url: null, estimated_hours: 10, is_completed: false, completed_at: null, proof_url: null, xp_reward: 100, created_at: '2026-02-25T00:00:00Z' },
        { id: 'vt6', stage_id: 'vstage-2', user_id: 'vineet-001', title: 'Deploy backend to Render.com', description: 'Live URL + GitHub README', task_type: 'apply', resource_url: null, estimated_hours: 2, is_completed: false, completed_at: null, proof_url: null, xp_reward: 70, created_at: '2026-02-25T00:00:00Z' },
      ],
    },
    {
      id: 'vstage-3',
      roadmap_id: 'vroadmap-001',
      stage_number: 3,
      title: 'Full-Stack Domain Project',
      description: 'Convert your domain knowledge into a deployable product. A health tracker or research paper manager.',
      skills_to_learn: ['React Basics', 'Full-Stack Integration', 'Docker'],
      resources: [
        { name: 'React Full Course — Hitesh Choudhary', url: 'https://youtube.com/playlist?list=PLu71SKxNbfoBAaWGtn9GA2PTw0HO0tXzq', type: 'video', platform: 'YouTube', is_free: true },
        { name: 'Docker Tutorial — TechWorld with Nana', url: 'https://youtube.com/playlist?list=PLy7NrYWoggjzfAHlUusx2wuDwfCrmJYcs', type: 'video', platform: 'YouTube', is_free: true },
        { name: 'MERN Stack Project — JS Mastery', url: 'https://youtube.com/playlist?list=PL6QREj8te1T7VSwkriBcEtvF_B8bKJKLG', type: 'video', platform: 'YouTube', is_free: true },
      ],
      projects: [{ name: 'Health Monitoring Dashboard', description: 'Patient logs, vitals tracking, analytics, and report PDF export', skills_practiced: ['React', 'Node.js', 'MongoDB', 'Chart.js', 'Docker'], difficulty: 'intermediate' }],
      estimated_weeks: 4,
      is_completed: false,
      completion_percentage: 0,
      order_index: 3,
      tasks: [
        { id: 'vt7', stage_id: 'vstage-3', user_id: 'vineet-001', title: 'Complete React fundamentals playlist', description: 'Hitesh Choudhary — 2 weeks sprint', task_type: 'learn', resource_url: 'https://youtube.com/playlist?list=PLu71SKxNbfoBAaWGtn9GA2PTw0HO0tXzq', estimated_hours: 10, is_completed: false, completed_at: null, proof_url: null, xp_reward: 90, created_at: '2026-03-20T00:00:00Z' },
        { id: 'vt8', stage_id: 'vstage-3', user_id: 'vineet-001', title: 'Build Health Monitoring Dashboard (full-stack)', description: 'React frontend + Node API + MongoDB', task_type: 'build', resource_url: null, estimated_hours: 16, is_completed: false, completed_at: null, proof_url: null, xp_reward: 130, created_at: '2026-03-20T00:00:00Z' },
        { id: 'vt9', stage_id: 'vstage-3', user_id: 'vineet-001', title: 'Containerise with Docker Compose', description: 'Docker Compose for full stack app', task_type: 'build', resource_url: null, estimated_hours: 4, is_completed: false, completed_at: null, proof_url: null, xp_reward: 80, created_at: '2026-03-20T00:00:00Z' },
        { id: 'vt10', stage_id: 'vstage-3', user_id: 'vineet-001', title: 'Deploy to Vercel + write architecture README', description: 'Live URL + GitHub README with screenshots', task_type: 'apply', resource_url: null, estimated_hours: 3, is_completed: false, completed_at: null, proof_url: null, xp_reward: 70, created_at: '2026-03-20T00:00:00Z' },
      ],
    },
    {
      id: 'vstage-4',
      roadmap_id: 'vroadmap-001',
      stage_number: 4,
      title: 'Positioning & Applications',
      description: 'Convert proof into industry positioning. Update LinkedIn, tailor resume, and apply to target roles.',
      skills_to_learn: ['LinkedIn Positioning', 'ATS Resume', 'Industry Outreach'],
      resources: [],
      projects: [],
      estimated_weeks: 3,
      is_completed: false,
      completion_percentage: 0,
      order_index: 4,
      tasks: [
        { id: 'vt11', stage_id: 'vstage-4', user_id: 'vineet-001', title: 'Rebuild LinkedIn headline and about section', description: 'Position as Applied Tech Leader + Researcher, not just academic', task_type: 'apply', resource_url: null, estimated_hours: 2, is_completed: false, completed_at: null, proof_url: null, xp_reward: 60, created_at: '2026-04-20T00:00:00Z' },
        { id: 'vt12', stage_id: 'vstage-4', user_id: 'vineet-001', title: 'Generate ATS resume from ZeroGap profile', description: 'Target: Research Analyst + VP Product + CTO roles', task_type: 'apply', resource_url: null, estimated_hours: 2, is_completed: false, completed_at: null, proof_url: null, xp_reward: 70, created_at: '2026-04-20T00:00:00Z' },
        { id: 'vt13', stage_id: 'vstage-4', user_id: 'vineet-001', title: "Apply to top 3 job matches", description: "BYJU'S Research Analyst, Unacademy VP Product, Deloitte Consultant", task_type: 'apply', resource_url: null, estimated_hours: 3, is_completed: false, completed_at: null, proof_url: null, xp_reward: 90, created_at: '2026-04-20T00:00:00Z' },
      ],
    },
  ],
};

export const VINEET_RESUME: ResumeRecord = {
  id: 'vresume-001',
  user_id: 'vineet-001',
  target_role_id: 'vr-001',
  ats_score: 74,
  keyword_match_score: 68,
  pdf_url: null,
  version: 1,
  is_latest: true,
  created_at: new Date().toISOString(),
  content_json: {
    basics: {
      name: 'Dr. Vineet Kumar Verma',
      email: 'vineetkumarverma@zerogap.in',
      phone: '+91 98765 43210',
      location: 'Lucknow, Uttar Pradesh',
      linkedin: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/',
      github: '',
      portfolio: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/',
    },
    summary: 'Ph.D in Computer Science with 10+ years of academic leadership, AI research, and EdTech curriculum engineering. Proven track record in building institutional academic programs, publishing 45+ research papers, and mentoring 500+ students. Transitioning into applied technology leadership with a focus on EdTech product strategy, AI integration, and Chief Technology Officer roles at mission-driven organizations.',
    skills: {
      technical: ['Python (Scripting & Data)', 'Machine Learning (Supervised/Unsupervised)', 'SQL & PostgreSQL', 'Data Analysis & Visualization', 'Research Methodology', 'System Design (Conceptual)', 'REST APIs (Learning)'],
      databases: ['MySQL', 'PostgreSQL', 'MongoDB (Basics)'],
      tools: ['MS Office Suite', 'MATLAB', 'Jupyter Notebooks', 'GitHub (Onboarding)', 'Postman (Learning)', 'Google Analytics'],
      soft: ['Academic Leadership', 'Strategic Planning', 'Stakeholder Communication', 'Research & Publication', 'Mentorship', 'Curriculum Engineering'],
    },
    education: [
      { degree: 'Ph.D — Computer Science & Engineering', institution: 'BBDNITM, Lucknow', location: 'Lucknow, UP', graduation: '2014', cgpa: 'Distinction', relevant_courses: ['Artificial Intelligence', 'Machine Learning', 'Database Systems', 'Algorithm Design', 'Research Methodology'] },
      { degree: 'M.Tech — Computer Science', institution: 'BBDNITM, Lucknow', location: 'Lucknow, UP', graduation: '2009', cgpa: '8.6/10', relevant_courses: ['Advanced Algorithms', 'Computer Networks', 'Operating Systems', 'Software Engineering'] },
    ],
    experience: [
      {
        title: 'Associate Professor & Department Head (CSE)',
        company: 'BBDNITM',
        location: 'Lucknow, UP',
        duration: '2014 – Present',
        points: [
          'Led a 20-member faculty team across the CSE department, managing curriculum planning, accreditation compliance, and academic research output for 800+ students annually.',
          'Designed and deployed 12 course modules in AI, ML, Data Structures, and Software Engineering — increasing student placement readiness by 34% over 3 years.',
          'Secured 3 government research grants (DST / AICTE) worth ₹42L, driving applied AI and healthcare informatics research projects.',
          'Mentored 500+ students; 6 guided Ph.D scholars; 45+ research papers published in SCI/Scopus-indexed journals and IEEE conferences.',
          'Introduced industry-academic collaboration programs with 8 regional IT companies, providing live project exposure to 200+ final-year students.',
        ],
      },
      {
        title: 'Research Consultant — AI & Healthcare Analytics',
        company: 'Independent / KGMU Lucknow Collaboration',
        location: 'Lucknow, UP',
        duration: '2019 – 2022',
        points: [
          'Collaborated with King George Medical University to build predictive ML models for early-stage disease detection using patient datasets of 10,000+ records.',
          'Reduced diagnostic pattern noise by 22% through feature engineering and ensemble model optimization in Python.',
          'Published 4 papers in healthcare informatics journals on AI-assisted diagnostics and clinical data interpretation.',
        ],
      },
    ],
    projects: [
      { name: 'Academic Portfolio Website', tech_stack: 'HTML, CSS, JavaScript', github_url: '', live_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/', status: 'Completed', points: ['Built personal academic portfolio showcasing 45+ publications, research grants, and mentorship work.', 'First deployed web project as part of tech upskilling roadmap — proof of execution discipline.'] },
      { name: 'Healthcare AI Diagnostic Model (Research)', tech_stack: 'Python, Scikit-learn, Pandas, Matplotlib, Jupyter', github_url: '', live_url: '', status: 'Completed', points: ['Developed ensemble ML model for early disease prediction on 10,000+ clinical records with KGMU Lucknow.', 'Achieved 87% prediction accuracy after feature engineering; reduced diagnostic noise by 22%.', 'Produced 4 peer-reviewed research papers published in Scopus-indexed journals.'] },
      { name: 'Student Performance Analytics Dashboard (In Progress)', tech_stack: 'React, Node.js, MongoDB, Chart.js', github_url: '', live_url: '', status: 'In Progress', points: ['Building a full-stack student tracker to monitor marks, placement readiness, and skill gaps for 300+ students.', 'Applying Node.js + React + MongoDB stack as proof of full-stack capability for industry transition.', 'Planned deployment to Vercel with Docker containerisation — targeted completion in 8 weeks.'] },
      { name: 'AI-Powered Curriculum Recommendation Engine (Planned)', tech_stack: 'Python, Flask, Scikit-learn, PostgreSQL', github_url: '', live_url: '', status: 'Planned', points: ['Designing an ML-driven system to recommend course modules to students based on career goal and skill gap data.', 'Plans to integrate with college LMS; targeting a live walkthrough within 12 weeks as industry transition proof.'] },
    ],
    certifications: [
      { name: 'NPTEL — Machine Learning', issuer: 'IIT Kharagpur', date: '2021', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
      { name: 'Data Science Specialization', issuer: 'Coursera — Johns Hopkins', date: '2020', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
      { name: 'Python for Data Science', issuer: 'IBM via Coursera', date: '2022', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
      { name: 'Leadership in Tech — Executive Program', issuer: 'IIM Lucknow', date: '2023', credential_url: 'https://linkedin.com/in/dr-vineet-kumar-verma-90b99a13/' },
      { name: 'Web Development Full Course (in progress)', issuer: 'Apna College / YouTube', date: '2026', credential_url: '' },
    ],
    achievements: [
      'Published 45+ research papers in SCI/Scopus-indexed journals and IEEE conferences over a 10-year career.',
      'Secured ₹42 Lakh in government research grants from DST and AICTE for applied AI research projects.',
      'Mentored 6 successful Ph.D scholars and 500+ undergraduate students across CSE programs.',
      'Ranked in Top 20% of academic peers nationally for research output and institutional contribution.',
      'Designed 12 curriculum modules that improved student placement readiness by 34% over 3 years.',
      'Collaborated with KGMU Lucknow on healthcare AI research published in 4 peer-reviewed journals.',
      'Introduced industry-academic bridge programs connecting 200+ students with 8 regional IT companies.',
    ],
    extracurricular: [
      { title: 'Department Head — CSE', organization: 'BBDNITM', duration: '2018–Present', description: 'Led department strategy, faculty management, and accreditation processes for NAAC/NBA.' },
      { title: 'Research Reviewer', organization: 'IEEE & Scopus Journals', duration: '2015–Present', description: 'Peer-reviewed 80+ research submissions across AI, ML, and computer vision domains.' },
      { title: 'Academic Mentor', organization: 'AICTE Approved Programs', duration: '2016–Present', description: 'Guided curriculum reform under AICTE 2.0 guidelines for outcome-based education.' },
    ],
    languages: ['English (Professional Fluency)', 'Hindi (Native)'],
    ats_keywords_injected: ['Machine Learning', 'Python', 'Data Analysis', 'Research', 'EdTech', 'Curriculum Design', 'Leadership', 'Strategic Planning', 'SQL', 'Academic', 'AI', 'Ph.D', 'Stakeholder Management', 'Mentor', 'Product Strategy'],
  },
};

export const VINEET_PROJECTS: GeneratedProject[] = [
  { id: 'vp1', user_id: 'vineet-001', project_title: 'Health Monitoring Dashboard', description: 'Full-stack patient vitals tracking system with analytics, PDF report generation, and a clean clinical UI. Designed to showcase domain-to-product conversion for healthcare AI positioning.', tech_stack: ['React', 'Node.js', 'MongoDB', 'Chart.js', 'PDFKit', 'Docker'], skills_practiced: ['React', 'REST APIs', 'Data Visualization', 'Docker', 'Deployment'], difficulty_level: 'intermediate', starter_code_url: null, github_template_url: null, step_by_step_guide: ['Design patient data schema: vitals, logs, doctor notes', 'Build Node.js + Express REST API with auth', 'Create React dashboard with Chart.js analytics', 'Add PDF report generation per patient', 'Containerise with Docker Compose', 'Deploy frontend to Vercel, backend to Render', 'Write architecture README with screenshots'], is_github_ready: true, created_at: vnow },
  { id: 'vp2', user_id: 'vineet-001', project_title: 'Research Paper Manager', description: 'Academic paper repository with tagging, search, citation tracking, and AI-powered abstract summarization. Perfect proof of domain + ML + product execution.', tech_stack: ['React', 'Node.js', 'PostgreSQL', 'Python (ML summaries)', 'Tailwind CSS'], skills_practiced: ['React', 'Node.js', 'PostgreSQL', 'Python ML', 'REST APIs'], difficulty_level: 'intermediate', starter_code_url: null, github_template_url: null, step_by_step_guide: ['Design paper schema: title, abstract, authors, tags, citations', 'Build search and filter API in Node.js', 'Add AI abstract summarizer using Python + Hugging Face', 'Build React UI with filtering, upload, and citation graph', 'Deploy full stack; write README'], is_github_ready: true, created_at: vnow },
  { id: 'vp3', user_id: 'vineet-001', project_title: 'Student Performance Tracker', description: 'Institutional dashboard tracking marks, placement readiness, skill gaps, and recommendations for 300+ students.', tech_stack: ['React', 'Node.js', 'MongoDB', 'Chart.js', 'Tailwind CSS'], skills_practiced: ['React', 'Node.js', 'MongoDB', 'Data Visualization'], difficulty_level: 'beginner', starter_code_url: null, github_template_url: null, step_by_step_guide: ['Design student schema: marks, skills, target roles', 'Build CRUD API for student records', 'Create analytics dashboard with role-wise breakdown', 'Add CSV export and placement report PDF', 'Deploy to Vercel + document for institutional sharing'], is_github_ready: true, created_at: vnow },
];

export const VINEET_PLAYLISTS = [
  { id: 'vpl1', yt_playlist_id: 'PLGjplNEQ1it8-0CmoljS5yeV-GlKSUEt0', title: 'Web Development Full Course', channel_name: 'Apna College', thumbnail_url: 'https://i.ytimg.com/vi/BsDoLVMnmZs/hqdefault.jpg', total_videos: 28, total_duration_seconds: 32400, skill_tags: ['HTML', 'CSS', 'JavaScript'], difficulty: 'beginner' as const, category: 'Web Development - Frontend', is_enrolled: true, completion_percentage: 100, match_score: 0.97 },
  { id: 'vpl2', yt_playlist_id: 'PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR', title: 'JavaScript Full Course', channel_name: 'CodeWithHarry', thumbnail_url: 'https://i.ytimg.com/vi/Dxf2cFu--Kg/hqdefault.jpg', total_videos: 30, total_duration_seconds: 36000, skill_tags: ['JavaScript', 'ES6', 'DOM'], difficulty: 'beginner' as const, category: 'Web Development - Frontend', is_enrolled: true, completion_percentage: 80, match_score: 0.95 },
  { id: 'vpl3', yt_playlist_id: 'PLwGdqUZWnOp3t3qT7pvAznwUDzKbhEcCc', title: 'Node.js & Express Full Course', channel_name: 'Thapa Technical', thumbnail_url: 'https://i.ytimg.com/vi/cF0RQmB5h04/hqdefault.jpg', total_videos: 22, total_duration_seconds: 28800, skill_tags: ['Node.js', 'Express', 'REST API'], difficulty: 'beginner' as const, category: 'Web Development - Backend', is_enrolled: true, completion_percentage: 35, match_score: 0.93 },
  { id: 'vpl4', yt_playlist_id: 'PLu71SKxNbfoBAaWGtn9GA2PTw0HO0tXzq', title: 'React Full Course', channel_name: 'Hitesh Choudhary', thumbnail_url: 'https://i.ytimg.com/vi/Gjnup-PuquQ/hqdefault.jpg', total_videos: 25, total_duration_seconds: 30600, skill_tags: ['React', 'Hooks', 'State'], difficulty: 'beginner' as const, category: 'Web Development - Frontend', is_enrolled: false, completion_percentage: 0, match_score: 0.96 },
  { id: 'vpl5', yt_playlist_id: 'PLy7NrYWoggjzfAHlUusx2wuDwfCrmJYcs', title: 'Docker for Beginners', channel_name: 'TechWorld with Nana', thumbnail_url: 'https://i.ytimg.com/vi/3c-iBn73dDE/hqdefault.jpg', total_videos: 18, total_duration_seconds: 21600, skill_tags: ['Docker', 'Containers', 'DevOps'], difficulty: 'beginner' as const, category: 'DevOps & Cloud', is_enrolled: false, completion_percentage: 0, match_score: 0.91 },
  { id: 'vpl6', yt_playlist_id: 'PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX', title: 'System Design Masterclass', channel_name: 'Gaurav Sen', thumbnail_url: 'https://i.ytimg.com/vi/quLrc3PbuIw/hqdefault.jpg', total_videos: 25, total_duration_seconds: 36000, skill_tags: ['System Design', 'Architecture', 'Scalability'], difficulty: 'advanced' as const, category: 'System Design', is_enrolled: false, completion_percentage: 0, match_score: 0.88 },
  { id: 'vpl7', yt_playlist_id: 'PLagDAQAkW7I2ATAjJa15FIYblJRDt2QSa', title: 'Machine Learning Full Course', channel_name: 'freeCodeCamp', thumbnail_url: 'https://i.ytimg.com/vi/i_LwzRVP7bg/hqdefault.jpg', total_videos: 20, total_duration_seconds: 43200, skill_tags: ['Machine Learning', 'Python', 'Scikit-learn'], difficulty: 'intermediate' as const, category: 'Data Science & ML', is_enrolled: true, completion_percentage: 100, match_score: 0.94 },
  { id: 'vpl8', yt_playlist_id: 'PLagDAQAkW7I0RH7oGKk_4QrE6T4P7gA-0', title: 'Full Stack MERN Project', channel_name: 'JavaScript Mastery', thumbnail_url: 'https://i.ytimg.com/vi/VsUzmlZfYNg/hqdefault.jpg', total_videos: 12, total_duration_seconds: 18000, skill_tags: ['React', 'Node.js', 'MongoDB', 'Full Stack'], difficulty: 'intermediate' as const, category: 'Web Development - Full Stack', is_enrolled: false, completion_percentage: 0, match_score: 0.90 },
];

export const VINEET_ACTIVITY_GRAPH: { date: string }[] = Array.from({ length: 3 }, (_, index) => {
  const date = new Date();
  date.setDate(date.getDate() - (2 - index));
  return { date: date.toISOString().slice(0, 10) };
});

export const VINEET_CHAT = [
  { role: 'user', content: 'I am an academic with a Ph.D in CS. How do I transition to a CTO role in EdTech?' },
  { role: 'assistant', content: "Your academic credibility is your strongest asset — most EdTech CTOs don't have a Ph.D. But the gap is execution proof: right now your profile says 'I know things', industry needs 'I built things'. The 3-step bridge: (1) Build 1 deployed project in your domain — Health Dashboard or Student Tracker — using Node.js + React. (2) Containerise it with Docker. (3) Write a LinkedIn post explaining what you built and why. That post + GitHub link will get you 5x more CTO conversations than 45 papers alone." },
  { role: 'user', content: 'Which role should I target first — CTO, VP Product, or Research Analyst?' },
  { role: 'assistant', content: "Start with Research Analyst at BYJU'S or Unacademy — 88% fit, highest probability of first offer. Use that role to get inside an EdTech product company and demonstrate tech leadership. Within 18 months you'll have the combination of academic credibility + industry track record that EdTech CTOs look for. The VP Product and CTO roles are 2 job-hops away, not 1. This is the fastest path." },
  { role: 'user', content: 'What is the single most important thing I should build in the next 30 days?' },
  { role: 'assistant', content: "The Student Performance Tracker. Here's why: (1) It matches your existing institutional work — you've literally done this as manual spreadsheets. (2) It's Node.js + React + MongoDB — the stack that closes your 3 biggest skill gaps. (3) It's a product a recruiter at BYJU'S or Unacademy immediately understands. Build it, deploy it to Vercel, write a 1-page README, push to GitHub. That one project converts you from 'academic' to 'builder' in their eyes." },
];
